const { PGlite } = require(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async()=>{
 const db = new PGlite();
 await db.exec("create role anon; create role authenticated; create role service_role; create table items(item_id text primary key); create table stocks(item_id text primary key, quantity integer check(quantity>=0)); insert into items values('a'),('b'); insert into stocks values('a',100),('b',50);");
 await db.exec(fs.readFileSync('supabase/migrations/20260929_01_withdrawals.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20260929_03_withdrawal_people.sql','utf8'));
 const ids = ['00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000003'];
 const create=(id,lines)=>db.query('select create_withdrawal($1,$2,$3,$4,$5,$6)',[id,'3236','',JSON.stringify(lines),'ตวัน','ตัวรองตวัน']);
 const finish=(id,status)=>db.query('select finish_withdrawal($1,$2)',[id,status]);
 const quantity=async()=> (await db.query("select quantity from stocks where item_id='a'")).rows[0].quantity;
 await create(ids[0],[{item_id:'a',quantity:60}]);
 assert.equal(await quantity(),100);
 await create(ids[0],[{item_id:'a',quantity:60}]);
 assert.equal((await db.query('select count(*)::int count from withdrawals')).rows[0].count,1);
 await assert.rejects(create(ids[1],[{item_id:'a',quantity:41}]));
 await assert.rejects(create(ids[1],[{item_id:'a',quantity:20},{item_id:'b',quantity:51}]));
 assert.equal((await db.query('select count(*)::int count from withdrawals')).rows[0].count,1);
 await finish(ids[0],'sent'); assert.equal(await quantity(),40);
 await finish(ids[0],'sent'); assert.equal(await quantity(),40);
 await assert.rejects(finish(ids[0],'cancelled'));
 await create(ids[1],[{item_id:'a',quantity:40}]);
 await finish(ids[1],'cancelled'); assert.equal(await quantity(),40);
 await create(ids[2],[{item_id:'a',quantity:40}]);
 await db.exec("update stocks set quantity=0 where item_id='a'");
 await assert.rejects(finish(ids[2],'sent'));
 assert.equal((await db.query('select status from withdrawals where id=$1',[ids[2]])).rows[0].status,'pending');
 const person = (await db.query('select requester_name,recipient_name,character_id from withdrawals where id=$1',[ids[0]])).rows[0];
 assert.deepEqual(person,{requester_name:'ตวัน',recipient_name:'ตัวรองตวัน',character_id:'3236'});
 await db.close(); console.log('PASS: reservations, overbooking, atomic rollback, idempotent create/send, cancellation, insufficient dispatch stock');
})().catch(e=>{console.error(e);process.exitCode=1});
